name: Build & Push Changed Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USER: yourdockerhubusername
  IMAGE_PREFIX: ecommerce

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: paths
        uses: dorny/paths-filter@v3
        with:
          filters: |
            adservice: src/adservice/**
            cartservice: src/cartservice/**
            checkoutservice: src/checkoutservice/**
            currencyservice: src/currencyservice/**
            emailservice: src/emailservice/**
            frontend: src/frontend/**
            loadgenerator: src/loadgenerator/**
            paymentservice: src/paymentservice/**
            productcatalogservice: src/productcatalogservice/**
            recommendationservice: src/recommendationservice/**
            shippingservice: src/shippingservice/**
            shoppingassistantservice: src/shoppingassistantservice/**

      - id: set_matrix
        env:
          AD: ${{ steps.paths.outputs.adservice }}
          CART: ${{ steps.paths.outputs.cartservice }}
          CHECKOUT: ${{ steps.paths.outputs.checkoutservice }}
          CURR: ${{ steps.paths.outputs.currencyservice }}
          EMAIL: ${{ steps.paths.outputs.emailservice }}
          FRONT: ${{ steps.paths.outputs.frontend }}
          LOAD: ${{ steps.paths.outputs.loadgenerator }}
          PAY: ${{ steps.paths.outputs.paymentservice }}
          PROD: ${{ steps.paths.outputs.productcatalogservice }}
          RECO: ${{ steps.paths.outputs.recommendationservice }}
          SHIP: ${{ steps.paths.outputs.shippingservice }}
          SHOP: ${{ steps.paths.outputs.shoppingassistantservice }}
        run: |
          add() { printf '{"service":"%s","context":"%s","dockerfile":"%s"}' "$1" "$2" "$3"; }
          list=()

          if [ "$AD" = "true" ]; then   list+=("$(add adservice src/adservice src/adservice/Dockerfile)"); fi
          if [ "$CART" = "true" ]; then list+=("$(add cartservice src/cartservice src/cartservice/src/Dockerfile)"); fi
          if [ "$CHECKOUT" = "true" ]; then list+=("$(add checkoutservice src/checkoutservice src/checkoutservice/Dockerfile)"); fi
          if [ "$CURR" = "true" ]; then list+=("$(add currencyservice src/currencyservice src/currencyservice/Dockerfile)"); fi
          if [ "$EMAIL" = "true" ]; then list+=("$(add emailservice src/emailservice src/emailservice/Dockerfile)"); fi
          if [ "$FRONT" = "true" ]; then list+=("$(add frontend src/frontend src/frontend/Dockerfile)"); fi
          if [ "$LOAD" = "true" ]; then list+=("$(add loadgenerator src/loadgenerator src/loadgenerator/Dockerfile)"); fi
          if [ "$PAY" = "true" ]; then list+=("$(add paymentservice src/paymentservice src/paymentservice/Dockerfile)"); fi
          if [ "$PROD" = "true" ]; then list+=("$(add productcatalogservice src/productcatalogservice src/productcatalogservice/Dockerfile)"); fi
          if [ "$RECO" = "true" ]; then list+=("$(add recommendationservice src/recommendationservice src/recommendationservice/Dockerfile)"); fi
          if [ "$SHIP" = "true" ]; then list+=("$(add shippingservice src/shippingservice src/shippingservice/Dockerfile)"); fi
          if [ "$SHOP" = "true" ]; then list+=("$(add shoppingassistantservice src/shoppingassistantservice src/shoppingassistantservice/Dockerfile)"); fi

          if [ ${#list[@]} -eq 0 ]; then
            echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
          else
            printf 'matrix={"include":[%s]}\n' "$(IFS=, ; echo "${list[*]}")" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: detect
    if: ${{ toJson(fromJson(needs.detect.outputs.matrix).include) != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: semver
        run: |
          IMAGE="${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service }}"
          LATEST=$(curl -fsSL "https://hub.docker.com/v2/repositories/${IMAGE}/tags/?page_size=100" \
                   | jq -r '[.results[].name | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))]
                             | sort_by(split(".")|map(tonumber)) | last // ""')
          if [ -z "$LATEST" ]; then
            NEW="0.0.1"
          else
            IFS='.' read -r MAJ MIN PAT <<<"$LATEST"
            PAT=$((PAT + 1))
            NEW="${MAJ}.${MIN}.${PAT}"
          fi
          echo "version=$NEW" >> "$GITHUB_OUTPUT"

      - uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.IMAGE_PREFIX }}-${{ matrix.service }}:${{ steps.semver.outputs.version }}
