name: EKS Create (Remote State)

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region"
        required: false
        default: "eu-west-2"
      cluster_name:
        description: "EKS cluster name"
        required: false
        default: "demo-eks"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TF_IN_AUTOMATION: "true"
      AWS_REGION: ${{ inputs.aws_region || secrets.AWS_REGION }}
      TF_BACKEND_BUCKET: ${{ secrets.S3_BACKEND_BUCKET }}
      TF_BACKEND_DDB_TABLE: ${{ secrets.S3_BACKEND_DDB_TABLE }}
      TF_BACKEND_KEY: "eks/terraform.tfstate"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Ensure S3 bucket and DynamoDB table exist
        run: |
          set -e
          BUCKET="${TF_BACKEND_BUCKET}"
          DDB="${TF_BACKEND_DDB_TABLE}"
          REGION="${AWS_REGION}"

          if ! aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
            if [ "$REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$BUCKET"
            else
              aws s3api create-bucket --bucket "$BUCKET" --create-bucket-configuration LocationConstraint="$REGION"
            fi
          fi
          aws s3api put-bucket-versioning --bucket "$BUCKET" --versioning-configuration Status=Enabled

          if ! aws dynamodb describe-table --table-name "$DDB" >/dev/null 2>&1; then
            aws dynamodb create-table               --table-name "$DDB"               --attribute-definitions AttributeName=LockID,AttributeType=S               --key-schema AttributeName=LockID,KeyType=HASH               --billing-mode PAY_PER_REQUEST
          fi

      - name: Terraform Init (S3 backend)
        working-directory: infra/aws-eks
        run: |
          terraform init             -backend-config="bucket=${TF_BACKEND_BUCKET}"             -backend-config="key=${TF_BACKEND_KEY}"             -backend-config="region=${AWS_REGION}"             -backend-config="dynamodb_table=${TF_BACKEND_DDB_TABLE}"             -backend-config="encrypt=true"

      - name: Terraform Apply
        working-directory: infra/aws-eks
        run: |
          terraform apply -auto-approve             -var="region=${AWS_REGION}"             -var="cluster_name=${{ inputs.cluster_name }}"
      
      - name: Upload kubeconfig artifact
        uses: actions/upload-artifact@v4
        with:
          name: eks-kubeconfig
          path: infra/aws-eks/kubeconfig
